export const MOTIVATIONAL_QUOTES = [
  "Quem age antes, fecha antes.",
  "Meta não é pressão, é direção.",
  "Quem segue processo, fecha contrato.",
  "Sem follow-up, não existe venda.",
  "Resultado é consequência de disciplina.",
  "Ação constante vence qualquer crise.",
  "Vendedor campeão aparece até nos dias difíceis.",
  "Quem desiste cedo, nunca descobre o quanto podia ganhar.",
  "Consistência constrói faturamento.",
  "Alta performance começa na mente.",
  "Vender é servir bem.",
  "Hoje eu planto, amanhã eu faturo.",
  "Sem ação, sem comissão.",
  "Vendedor fraco espera motivação, vendedor forte cria.",
  "Quem entra com dúvida, sai sem venda.",
  "Confiança não se explica, se transmite.",
  "Postura vende antes da proposta.",
  "Quem faz todo dia, colhe todo mês.",
  "Venda não é pico, é rotina.",
  "Pequenas ações diárias criam grandes comissões.",
  "Consistência vence talento disperso.",
  "Não é intensidade ocasional, é frequência.",
  "Quem aparece sempre, fecha sempre.",
  "Quem age todo dia não depende de sorte.",
  "Venda é repetição bem feita.",
  "Hoje é dia de vender, não de esperar.",
  "Venda acontece fora da zona de conforto.",
  "Faça de todo lead uma chance real.",
  "Foco no processo, fé no resultado.",
  "Vendedor campeão faz o básico todos os dias.",
  "Disciplina hoje, comissão amanhã.",
  "Quem domina a conversa, conduz o fechamento.",
  "Venda é treino diário.",
  "Venda não é sorte, é método.",
  "Quem aparece todo dia, é lembrado.",
  "Constância transforma potencial em dinheiro.",
  "Alta performance começa antes do expediente.",
  "Venda acontece quando você acredita primeiro.",
  "Persistência constrói faturamento.",
  "Objeção é sinal de interesse.",
  "Vendedor preparado não teme meta.",
  "A melhor técnica é executar.",
  "Sem ação, sem resultado.",
  "Confiança fecha mais que desconto.",
  "Processo executado gera previsibilidade.",
  "Quem não desiste, fecha.",
  '"A melhor maneira de prever o futuro é criá-lo." - Peter Drucker',
  '"Disciplina é a ponte entre metas e realizações." - Jim Rohn',
  '"Onde o foco vai, a energia flui." - Tony Robbins',
  '"Sucesso é sua obrigação, não uma opção." - Grant Cardone',
  '"Pessoas de sucesso fazem o que as pessoas comuns não querem fazer." - Brian Tracy',
  '"Posso aceitar o fracasso, mas não posso aceitar não tentar." - Michael Jordan',
  '"Descanso no final, não no meio." - Kobe Bryant',
  '"Disciplina é liberdade." - Jocko Willink',
  '"Sonhar grande e sonhar pequeno dá o mesmo trabalho." - Jorge Paulo Lemann',
  '"Não existe sucesso sem desconforto." - Flávio Augusto',
  '"Quem resolve problema cresce." - Luiza Helena Trajano',
  '"Eu acredito na sorte, mas acredito muito mais no trabalho." - Silvio Santos',
  '"Ideia boa sem execução não vale nada." - Murilo Gun',
  '"Quem não controla o processo não controla o resultado." - Thiago Nigro',
  '"Quem se adapta mais rápido, vence." - Ricardo Amorim',
  '"Disciplina é fazer o que precisa ser feito, mesmo sem vontade." - Carlos Wizard',
  '"O jogo é simples: quem executa, ganha." - Erico Rocha'
];
